### Get all contacts
GET https://project1-h052.onrender.com/contacts

### Get contact by Id
GET http://project1-h052.onrender.com/contacts/65db9ddc1d8ecdc82600525b

### Create a contact
POST http://project1-h052.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"June 19, 2000"
}

### Put contact
PUT http://project1-h052.onrender.com/contacts/65db9ddc1d8ecdc82600525b HTTP/1.1
Content-Type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"June 19, 2000"
}

### Delete Contact
DELETE http://project1-h052.onrender.com/contacts/65db9ddc1d8ecdc82600525b